<a href="https://colab.research.google.com/github/aleks-haksly/AI/blob/main/L1/lecture_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow import keras
from keras.datasets import mnist
from keras.models import Sequential # импортируем класс создания модели (последовательный)
from keras.layers import Dense # импортируем полносвязные слои

In [1]:
import numpy as np

In [7]:
model = Sequential()
# 1. добавляем полносвязный слой с 2 входами и 2 выходами
model.add(Dense(2,input_dim=2, use_bias=False))
# 2. далее еще один слой число входов авто, число выходов 1.
model.add(Dense(1, use_bias=False))

In [8]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 4         
                                                                 
 dense_3 (Dense)             (None, 1)                 2         
                                                                 
Total params: 6 (24.00 Byte)
Trainable params: 6 (24.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Non-trainable params: параметры, которые не требуется изменять при обучении модели

In [10]:
# При создании модели веса генерируются автоматически случайным образом.
weights = model.get_weights()
weights

[array([[ 0.51889765,  0.7904781 ],
        [ 0.27979243, -0.9374845 ]], dtype=float32),
 array([[ 0.79024756],
        [-0.1755265 ]], dtype=float32)]

In [15]:
# Также их можно установить вручную
w1 = 0.42
w2 = 0.15
w3 = -0.56
w4 = 0.83
w5 = 0.93
w6 = 0.02
# Веса в 1 и 2 слоях
L1 = np.array([[w1, w3],[w2, w4]])
L2 = np.array([[w5,], [w6,]])
model.set_weights([L1, L2])

In [16]:
model.get_weights()

[array([[ 0.42, -0.56],
        [ 0.15,  0.83]], dtype=float32),
 array([[0.93],
        [0.02]], dtype=float32)]

In [17]:
# Положим входные значения равны:
X1 = 7.2
X2 = -5.8

In [23]:
# создаем входной набор данных
x_train  = np.expand_dims(np.array([X1, X2]), 0) # ~reshape чтобы был двумерный набор, для этого добавляем ось
x_train

array([[ 7.2, -5.8]])

In [24]:
model.predict(x_train) # Предикт от модели, также он просто равен произведению матриц

1/1 [==============================] - 0s 190ms/step


array([[1.8262998]], dtype=float32)

In [26]:
np.matmul(np.array([X1, X2]), L1) # То же, что и np.array([X1, X2]) @ L1

array([ True,  True])

In [28]:
np.array([X1, X2]) @ L1 @ L2 # Предикт от модели, также он просто равен произведению матриц

array([1.8263])